import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { Navbar, NavbarBrand, NavbarContent, NavbarItem, Link, Input, DropdownItem, DropdownTrigger, Dropdown, DropdownMenu, Avatar } from "@nextui-org/react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='light'>
      <body>
        <Providers>
          <header>
            <Navbar isBordered classNames={{
              item: [
                "flex",
                "relative",
                "h-full",
                "items-center",
                "data-[active=true]:after:content-['']",
                "data-[active=true]:after:absolute",
                "data-[active=true]:after:bottom-0",
                "data-[active=true]:after:left-0",
                "data-[active=true]:after:right-0",
                "data-[active=true]:after:h-[2px]",
                "data-[active=true]:after:rounded-[2px]",
                "data-[active=true]:after:bg-secondary",
              ],
            }}>
              <NavbarContent>
                <NavbarContent style={{ display: 'flex', justifyContent: 'center' }}>
                  <NavbarItem isActive>
                    <Link color="secondary" href="#">
                      Home
                    </Link>
                  </NavbarItem>
                  <NavbarItem >
                    <Link href="#" aria-current="page" color="foreground">
                      Blog
                    </Link>
                  </NavbarItem>
                  <NavbarItem>
                    <Link color="foreground" href="#">
                      Tags
                    </Link>
                  </NavbarItem>
                  <NavbarItem>
                    <Link color="foreground" href="#">
                      Resume
                    </Link>
                  </NavbarItem>
                  <NavbarItem>
                    <Link color="foreground" href="#">
                      Contact
                    </Link>
                  </NavbarItem>
                </NavbarContent>
              </NavbarContent>
            </Navbar>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
